### ISSUE TITLE
Wrong modulo value for integer truncation operations

### ISSUE THREAD

**Issue by icvidal** [GRISHNOV/Fletcher_checksum#1]
Hi!

All modulo operations used to truncate the length of each integer to fit in a certain numbers of bit are wrong. For example:

`
for index in range(len(data)):
            sum1 = (sum1 + data[index]) % 255
`

Should be corrected to:

`
for index in range(len(data)):
            sum1 = (sum1 + data[index]) % 256
`

Because the modulo operation in the form of (A % B) is going to let A be in the range of 0 to B - 1. Using modulo % 255 for modulo will limit integers up to the value of 254 instead of 255 as desired.

The same applies to all other values.

**Comment by GRISHNOV** [comment]
Hi! 

As far as I understand, using [255](https://en.wikipedia.org/wiki/Fletcher%27s_checksum#Review_of_simple_checksums) is okay

**Comment by icvidal** [comment]
Hi

I've missed your previous reply since I was on a travel. It's not OK.
Think of this:

X % 2 can be either 0 or 1
X % 10 can be a number from 0 to 9
X % 100 can be a number between 0 and 100
X % 255 can be a number between 0 and 254. So there is one missing number
since the purpose is to truncate the value to 8 bits which should include
255.

Best,
Iván
